// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"golang-bootcamp-1/internal/admin/repository"
	admin3 "golang-bootcamp-1/internal/admin/transport/http"
	admin2 "golang-bootcamp-1/internal/admin/usecase"
	forgot_password2 "golang-bootcamp-1/internal/forgot-password/repository"
	"golang-bootcamp-1/internal/forgot-password/transport/http"
	forgot_password3 "golang-bootcamp-1/internal/forgot-password/usecase"
	oauth2 "golang-bootcamp-1/internal/oauth/repository"
	"golang-bootcamp-1/internal/oauth/transport/http"
	oauth3 "golang-bootcamp-1/internal/oauth/usecase"
	product_category2 "golang-bootcamp-1/internal/product-category/repository"
	"golang-bootcamp-1/internal/product-category/transport/http"
	product_category3 "golang-bootcamp-1/internal/product-category/usecase"
	"golang-bootcamp-1/internal/register/transport/http"
	register2 "golang-bootcamp-1/internal/register/usecase"
	"golang-bootcamp-1/internal/user/usecase"
	"golang-bootcamp-1/pkg/mail/mailtrap"
	"golang-bootcamp-1/pkg/media/cloudinary"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeRegisterHandler(db *gorm.DB, userUc usecase.IUserUseCase) *register.RegisterHandler {
	iMail := mail.NewMailUsecase()
	iRegisterUsecase := register2.NewRegisterUseCase(userUc, iMail)
	registerHandler := register.NewRegisterHandler(iRegisterUsecase)
	return registerHandler
}

func InitializeOauthHandler(db *gorm.DB, userUc usecase.IUserUseCase) *oauth.OauthHandler {
	iOauthClientRepo := oauth2.NewOauthClientRepo(db)
	iOauthAccessTokenRepo := oauth2.NewOauthAcces(db)
	iOauthRefreshTokenRepo := oauth2.NewOauthRefreshTokenRepo(db)
	iAdminRepository := admin.NewAdminRepository(db)
	iAdminUsecase := admin2.NewAdminUsecase(iAdminRepository)
	iOauthUseCase := oauth3.NewOauthUseCase(iOauthClientRepo, iOauthAccessTokenRepo, iOauthRefreshTokenRepo, userUc, iAdminUsecase)
	oauthHandler := oauth.NewOauthHandler(iOauthUseCase)
	return oauthHandler
}

func InitializeForgotPasswordHanlder(db *gorm.DB, userUc usecase.IUserUseCase) *forgot_password.ForgotPasswordHandler {
	iForgotPasswordRepo := forgot_password2.NewForgotPasswordRepository(db)
	iMail := mail.NewMailUsecase()
	iForgotPasswordUsecase := forgot_password3.NewForgotPasswordUsecase(iForgotPasswordRepo, userUc, iMail)
	forgotPasswordHandler := forgot_password.NewForgotPasswordHandler(iForgotPasswordUsecase)
	return forgotPasswordHandler
}

func InitializeAdminHandler(db *gorm.DB) *admin3.AdminHandler {
	iAdminRepository := admin.NewAdminRepository(db)
	iAdminUsecase := admin2.NewAdminUsecase(iAdminRepository)
	adminHandler := admin3.NewAdminHandler(iAdminUsecase)
	return adminHandler
}

func InitializeProductCategoryHandler(db *gorm.DB) *product_category.ProductCategoryHandler {
	iProductCategory := product_category2.NewProductCategoryRepository(db)
	iMedia := media.NewMediaUsecase()
	iProductCategoryUsecase := product_category3.NewProductCategoryUsecase(iProductCategory, iMedia)
	productCategoryHandler := product_category.NewProductCategoryHandler(iProductCategoryUsecase)
	return productCategoryHandler
}
